### ISSUE TITLE
are there any alternative api clients or client libraries?

### ISSUE THREAD

**Issue by whysthatso** [Gandi/gandi.cli#314]
now that the 'official' python client is deprecated, is there a list anywhere of available alternatives, if any?

**Comment by mardiros** [comment]
Hello @whysthatso 

The offical python client is deprecrated because it consume the v3 api, and there will no future development here.

https://doc.rpc.gandi.net/overview.html

At the moment, we don't plan to create a CLI / api wrapper for the V5 API yet.

So unfortunatly there is no official alternatives right now.

The new api is documented here ; https://api.gandi.net/docs/

**Comment by whysthatso** [comment]
@mardiros yes, i understand the state of the official client and the gandi api in general. i was hoping this issue could stay open as a place for people to post or inquire about unofficial clients or library implementations.
