### ISSUE TITLE
More charming hostname generator

### ISSUE THREAD

**Issue by soulshake** [Gandi/gandi.cli#92]
At present, names are automatically generated for VMs and instances in the following format:

`temp1415214477`

Would any functionality be lost if we were to use a more creative naming scheme?
e.g. `gandi vm delete temp\*` ?

For inspiration, see [names-generator.go](https://github.com/docker/docker/blob/master/pkg/namesgenerator/names-generator.go).

**Comment by grigouze** [comment]
Maybe this https://pypi.python.org/pypi/names/ or https://pypi.python.org/pypi/fake-factory ?

**Comment by soulshake** [comment]
What? Use something that wasn't invented here?! */me riots*

adjectives = ['thursday', 'guzzling', 'thirsty', 'grumbling']
names = ['grigouze', 'soulshake', 'kalou']
hostname = random.choice(adjectives) + '-' + random.choice(names)

We could autogenerate names from all the users who have contributed to the Gandi CLI :)
And/or have a list of our favorite badasses, à la names-generator.go.

**Comment by wdauchy** [comment]
to be exact, vm hostname are now in the form of "vmXXXXXX"

we were also talking about the possibility to auto complete resource names with tabulation key.

So I would prefer to type
$ gandi vm start vm<tab><tab>
in order to find the one I want

string matching could be also interesting:
$ gandi vm stop vm*

**Comment by kalou** [comment]
adjectives.append('trolling')

Chosing a hostname for a temporary VM is friction indeed.
That kind of feature should go in the API and name generation code removed from the CLI.

**Comment by grigouze** [comment]
@soulshake I prefer something don't invented here because I don't want to maintain these kind of code. It's just funny not mandatory.

Use someone's code is good :D

**Comment by gdchamal** [comment]
for information I had to build such rule for docker machine gandi driver. I think generating such default name should be done API side as @kalou said.

**Comment by sayoun** [comment]
Three things:

* this name generation thing should indeed be done in the API and not in the CLI, until then it's fine as it is now (and improved in the last release using @wdauchy patch for a prefix based on resource type).
* we must handle "string matching" (like`vm*`) as suggested by @wdauchy this will  be a nice addition until we have some real shell completion
* we should try to make the shell completion work (I still got a piece of code from @kalou somewhere about that)

**Comment by kalou** [comment]
@sayoun IIRC I changed things in it, just in case PR'd it

**Comment by kalou** [comment]
After starting to look at it for real - @grigouze proposals are fake names generators handling names and addresses but do not cover hostnames (unless you like "Georges" as a hostname). This issue is 7th on a google search for "python hostname generator".

That was just for the fun of it anyway. I'll close this and try to implement a first simple id-based name in the API soon.
